development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:db2008c915b8b27e804ac27d8ce37f80@hammerjaw.redistogo.com:10490/
  channel_prefix: instant_messaging_production
